# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-23 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_recorded', models.DateTimeField(null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preassure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('windspeed', models.PositiveSmallIntegerField()),
                ('solar_radiation', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newentry.WeatherStations'),
        ),
    ]
