# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-05 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_recorded', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_recorded', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('windspeed', models.PositiveSmallIntegerField(null=True)),
                ('solar_radiation', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, null=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newentry.WeatherStations'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newentry.Sensors'),
        ),
    ]
