# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-23 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='preassure',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='solar_radiation',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='time_recorded',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='windspeed',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherstations',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
