# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-23 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newentry', '0002_auto_20170723_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
