# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newentry', '0003_auto_20170723_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_recorded', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('preassure', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.PositiveIntegerField()),
                ('mac', models.CharField(max_length=17)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newentry.Sensors'),
        ),
    ]
