# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-05 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newentry', '0004_auto_20170805_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='sensorId',
        ),
    ]
